version: "1"

services:
  # ---------------------- FRONTEND ----------------------
  - type: web
    name: taxpal-frontend
    env: static
    rootDir: mean-app/client
    buildCommand: npm install && npm run build
    staticPublishPath: dist/dum/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  # ---------------------- BACKEND -----------------------
  - type: web
    name: taxpal-backend
    env: node
    rootDir: mean-app/server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false       # You’ll set this manually in Render’s dashboard
      - key: PORT
        value: 10000      # optional, Render auto-assigns if not set
