services:
  - type: web
    name: taxpal-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/dum/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production